### PR TITLE
added linter

### PR DESCRIPTION
**Pull request by arikarim**
This is our completed New York Times clone page project.
We used Html and Css, Linter for this project. 
This is our develop-branch and we ask for a pull request to merge the code into the main branch.

### CODE REVIEW

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Changes Required :recycle: 
Hello team! Thanks for your efforts to make it here. :smile: Before moving on there are some things that need to be done.


- [ ] For the part above, please align the hamburger menu and the rest.
- [ ] Please mimic the page and make your search button and the rest as in the page.
- [ ] Please give some padding to the elements on the right and center them in their container. (Login and Subscribe)
- [ ] Please use The New York Times logo in the center and make it as a link.


- [ ] Your editor's Pick moved right too much. Please locate it a little bit left and try to show it as on the page.


- [ ] Your theory of inflation is just an image and you spread the writings behind the places. Instead please use separated images and position them one by one.


- [ ] You can give some style to the Read comments and the social icons up there. 
- [ ] Please decrease the gap between the more in space and most popular parts.
- [ ] On the original page there is a part as suggested newsletters for you. Try to implement this part with it.


- [ ] Please decrease the width of the footer and make it as on the original page.

Team, so far so good. :+1: Please fix the issues mentioned above and submit for a re-review.
If you have any questions at all, reach out to me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by arikarim** [comment]
the theory of inflation is one picture and as required i can not cut it into 8 pieces and although its easy styling it using greed, hope you understand.

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @EL28DEV and @arikarim  , I am Abdulaziz Redi Ali, your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

- [ ] The page shouldn't scroll horizontally fix the overflow and horizontal scrolling.
- [ ] Remove the gap between the most popular articles and suggested articles.
- [ ] Make the navigation bar fixed to the top of the page
- [ ] Add more content to the readme file
- [ ] Remove the gap in the bottom section
gap

- [ ] Fix the footer, it should be in the center of the page and have similar look to the original 

| Your Copy | Original | 
| :---:         |     :---:      |
|footer_copy|footer_original|

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by arikarim** [comment]
fixed the gap problem and the footer is in the center.
the navigation bar is in the Top-Left corner of the page (humberger icon),

**Review by ioilmio — CHANGES_REQUESTED** [review]
# Hello @arikarim @EL28DEV 👋🏽 
### Good work till now but there are a couple of fixes that need to be done.
### Changes required 🔴 
## Please always refer to the original page [here](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)

### Navbar
- Refer to notes in screenshot
image
- Text is not aligned correctly under the photo
image


### Main content 
- Elements are overlapping each other please fix them;
image
- Align the caption properly
image
- Icons are squeezed, please fix them;
image

### Footer 
- Text is overlapped by the border, please fix it;
image

# General requirements:
## Edit your readme file;
## Be more descriptive with your pull request and commit messages;
## Theory of inflation is an image without text, practice grid, insert text in and place it correctly;
## Navbar should be sticky;

### 👍🏽  The project is taking shape so keep it up like that;

~~ For further info you can reach me on Slack @illuminatosalvatore;
Happy coding 💻

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @arikarim   ! :wave: :wave:

#### You have done well so far :clap: However, you have not made all the previously requested changes. Kindly work on them, as well as the new ones and submit them for another code review.


**Recommended**

**General**
- [ ] Use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension to help with the varying font-sizes and family required.
- [ ] You have a horizontal overflow, please fix it.
- [ ] Just as the previous code reviewer stated, always refer to the [actual](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0) site.

**Navigation bar**
- [ ] It should have a fixed position (it sticks to the top part of the screen) 
([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

- [ ] Adjust the navigation bar to look as similar as possible to that of the actual site.
**Original**
Screenshot (2)

**Your clone**
Screenshot (3)

- [ ] Text is not aligned correctly under the photo.

**Your clone**
Screenshot (4)

**Main Content**
- [ ] The elements are not aligned properly.
**Your clone**
image

- [ ] Refer to the NYT site for what the icons should look like.
**Your clone**
Screenshot (7)

**Footer**
- [ ] Refer to the NYT clone to make the minor changes in this section by comparing. 

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by arikarim** [comment]
i fixed the navbar to sticky and alined all the paragraphs and captions
hope to get a better result

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

**Pull request merged**
